apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: react-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: react-app
  template: 
    metadata:
      labels:
        app: react-app
    spec: 
      containers:
      - name: react-app
        image: haihengly/react-app:v1.1
        ports:
        - containerPort: 3000